# Generated by Django 5.1.2 on 2024-10-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(upload_to='', verbose_name=models.ImageField(upload_to=None, verbose_name='nil'))),
                ('full_name', models.CharField(max_length=200)),
                ('cohort', models.CharField(max_length=225)),
                ('program', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=225)),
                ('date_joined', models.DateField(verbose_name=models.DateField(verbose_name='1995-05-02'))),
                ('rating', models.FloatField(verbose_name=models.FloatField(verbose_name='2.5'))),
            ],
        ),
    ]
