# Generated by Django 5.1.2 on 2024-10-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('New_App', '0003_alter_student_profile_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='cohort',
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cohort_name', models.CharField(max_length=200)),
                ('date_join', models.DateTimeField(auto_now_add=True)),
                ('students', models.ManyToManyField(to='New_App.student')),
            ],
        ),
    ]
