# Generated by Django 5.1.2 on 2024-10-29 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('New_App', '0004_remove_student_cohort_cohort'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cohort',
            old_name='Cohort_name',
            new_name='cohort_name',
        ),
        migrations.RenameField(
            model_name='student_profile',
            old_name='Date_of_birth',
            new_name='date_of_birth',
        ),
    ]
